### ISSUE TITLE
CRUD master stok, obat dan supplier

### ISSUE THREAD

**Issue by fachiri** [fachiri/sindika#11]
## Ceklis

- [x] (Stock) Form harga atau biaya itu pake format rupiah. Pake advance form stisla
- [x] (Medicine) Tabel data obat itu hanya nama obat dan gambar obat (semacam preview kecil. gambarnya bungkus dgn tag a)
- [x] (Medicine) Halaman detail obat
- [x] (Supplier) Form no. handphone pake format +62. Pake advance form stisla
- [x] (Supplier) Lengkapi detail supplier. Isi tabelnya nama obat, tanggal masuk dan jumlah
- [x] (Stock) Tambah input form _expired_date_

**Comment by fauzan-radji** [comment]
Tag `<a><img ... /></a>` nanti `href` nya ngarah ke mana?

**Comment by fachiri** [comment]
asset gambarnya

**Comment by fachiri** [comment]
tambah input form _expired_date_ di data stock @fauzan-radji 
![image](https://github.com/fachiri/sindika/assets/96768471/e8563c1b-fbe2-47d0-bc0b-ac044fa80fd4)
