### ISSUE TITLE
Konfirmasi Hapus Data Master dengan Verifikasi Password

### ISSUE THREAD

**Issue by fachiri** [fachiri/sindika#7]
## Deskripsi Masalah
Saat ini, penghapusan data master tidak melibatkan langkah-langkah konfirmasi yang cukup, sehingga berpotensi menimbulkan penghapusan yang tidak diinginkan.

## Langkah-Langkah
**1. Konfirmasi Terkait Hapus**
Ketika pengguna mengklik tombol hapus untuk data master, akan muncul pesan konfirmasi yang menjelaskan bahwa data terkait juga akan dihapus.
**2. Verifikasi Password Sebelum Penghapusan**
Sebelum data master dihapus, pengguna akan diminta memasukkan password akun untuk memverifikasi tindakan ini.

## Checklist

- [x]  Modal konfirmasi yang menyebutkan penghapusan data terkait.
- [x]  Input password

## Konteks Tambahan

Langkah-langkah ini bertujuan untuk menambah lapisan keamanan dan mencegah penghapusan data yang tidak disengaja.

**Comment by fauzan-radji** [comment]
Keknya bisa sih kak lewat object `Request $request` dpe form data

**Comment by fachiri** [comment]
Oke sipl

**Comment by fachiri** [comment]
oke ini sudah
